### ISSUE TITLE
Produces confusing error on empty input

### ISSUE THREAD

**Issue by ModProg** [rs-tml/rstml#37]
Parsing an empty input yields:
> Object parsing failed, but no additional info was provided

I'd argue that this should just return an empty `Vec<Node>`, but if you insist on an error it should be more descriptive.

Test:

```rs
#[test]
fn test_empty_input() -> Result<()> {
    let tokens = quote! {};
    let nodes = parse2(tokens)?;

    assert!(nodes.is_empty());

    Ok(())
}
```

**Comment by vldm** [comment]
Yes, i agree with you. It should return empty `Vec` instead of returning error.
