### ISSUE TITLE
Correct the readme attribution of stoically.

### ISSUE THREAD

**Issue by karoofish** [rs-tml/rstml#47]
Hi,

Currently, in the README, you have a sentence that incorrectly states that "The author of original syn-rsx retired, end left new features without attention stoically#49".

You might want to word this and the related sentences about leaving things unattended, differently, as it reads like he abandoned the project, as apposed to [passing away(dying)](https://github.com/stoically/temporary-containers/issues/618). 

Regards

**Comment by vldm** [comment]
Hi, sorry, at the time of writing that part i didn't know it.
I will fix text with the correct term, and link.

Thank you for suggestion.
