### ISSUE TITLE
why no `Parser::default()`

### ISSUE THREAD

**Issue by zahash** [rs-tml/rstml#51]
instead of `Parser::new(ParserConfig::default())`
why not `Parser::default()`

```rs
impl Default for Parser<Infallible> {
    fn default() -> Self {
        Self {
            config: ParserConfig::default(),
        }
    }
}
```

**Comment by vldm** [comment]
Usually when you need Parser, you also need to customize config. But if you create a pr, I will accept it.

**Comment by zahash** [comment]
@vldm 
already made one 😊

https://github.com/rs-tml/rstml/pull/52
